CREATE TABLE IF NOT EXISTS clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(40),
    email VARCHAR(160)
);

CREATE TABLE IF NOT EXISTS employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    phone VARCHAR(40),
    email VARCHAR(160)
);

CREATE TABLE IF NOT EXISTS services (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    duration_minutes INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS salon_settings (
    id INTEGER PRIMARY KEY,
    salon_name VARCHAR(160) NOT NULL,
    address VARCHAR(200),
    phone VARCHAR(40),
    email VARCHAR(160),
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    service_id INTEGER NOT NULL,
    appointment_date DATE NOT NULL,
    start_time TIME NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payment_type VARCHAR(20) NOT NULL,
    CONSTRAINT fk_appointment_client FOREIGN KEY (client_id) REFERENCES clients(id),
    CONSTRAINT fk_appointment_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_appointment_service FOREIGN KEY (service_id) REFERENCES services(id),
    CONSTRAINT chk_appointment_status CHECK (status IN ('ZAKAZAN', 'OTKAZAN', 'ZAVRSEN')),
    CONSTRAINT chk_payment_type CHECK (payment_type IN ('CASH', 'CARD'))
);
